import{a as g,S as L,i as b}from"./assets/vendor-89feecc5.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))i(o);new MutationObserver(o=>{for(const n of o)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function e(o){const n={};return o.integrity&&(n.integrity=o.integrity),o.referrerpolicy&&(n.referrerPolicy=o.referrerpolicy),o.crossorigin==="use-credentials"?n.credentials="include":o.crossorigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function i(o){if(o.ep)return;o.ep=!0;const n=e(o);fetch(o.href,n)}})();const w="41495993-e4e29dd1119c53de35b82b765",v=document.getElementById("search-form"),d=document.getElementById("search-input"),u=document.getElementById("gallery"),f=document.getElementById("loader"),h=document.getElementById("load-more");let a=1;v.addEventListener("submit",$);h.addEventListener("click",B);function $(r){r.preventDefault();const t=d.value.trim();t!==""&&(E(),p(),m(t).then(e=>{e.hits.length===0?l("Вибачте, за вашим запитом не знайдено зображень. Будь ласка, спробуйте ще раз!"):(y(e.hits),I())}).catch(e=>{l("Виникла помилка під час отримання зображень. Будь ласка, спробуйте пізніше."),console.error("Помилка отримання зображень:",e)}).finally(()=>{s()}))}async function m(r,t=1){const e=`https://pixabay.com/api/?key=${w}&q=${r}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}`;try{return(await g.get(e)).data}catch(i){throw i}}function y(r){const t=r.map(e=>`
        <a href="${e.largeImageURL}" class="gallery-item" data-lightbox="gallery">
          <img src="${e.webformatURL}" alt="${e.tags}">
          <div class="info">
            <p>${e.likes} лайків</p>
            <p>${e.views} переглядів</p>
            <p>${e.comments} коментарів</p>
            <p>${e.downloads} завантажень</p>
          </div>
        </a>
      `).join("");u.innerHTML=t}function E(){u.innerHTML=""}function I(){new L(".gallery a").refresh()}function p(){f.style.display="block"}function s(){f.style.display="none"}function l(r){b.error({title:"Помилка",message:r,position:"topCenter",timeout:5e3})}async function B(){p(),a++;const r=d.value.trim();try{const t=await m(r,a);t.hits.length>0?(y(t.hits),x()):(s(),h.style.display="none",l("Вибачте, ви досягли кінця результатів пошуку."))}catch(t){s(),l("Виникла помилка під час отримання додаткових зображень. Будь ласка, спробуйте пізніше."),console.error("Помилка отримання зображень:",t)}finally{s()}}function x(){const r=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
